### ISSUE TITLE
missing `.sigstore` files for 3.4.0 release

### ISSUE THREAD

**Issue by chenrui333** [sigstore/sigstore-python#1171]
missing `.sigstore` files for 3.4.0 release 

relates to https://github.com/Homebrew/homebrew-core/pull/193655

cc @woodruffw

**Comment by woodruffw** [comment]
That was intentional -- the `.sigstore` files were being mostly uploaded as smoketest artifacts, and we're dropping them now that attestations are enabled directly on PyPI itself:

https://github.com/sigstore/sigstore-python/blob/d60ec7b7fb718d67d38161e5813bc6065d0215ce/.github/workflows/release.yml#L130

Were you verifying those manually before?

**Comment by chenrui333** [comment]
yeah, it is part of the brew test.

**Comment by woodruffw** [comment]
Gotcha! I followed up on https://github.com/Homebrew/homebrew-core/pull/193655 with some alternative artifacts/strategies for testing.

Closing for now since this isn't a bug per se.
