### ISSUE TITLE
Avoid reading input files to memory

### ISSUE THREAD

**Issue by jku** [sigstore/sigstore-python#158]
The API uses `bytes` as type for all file contents. This is fine for certs and signatures, but the input files can be arbitrarily large: the API should not force reading input files to memory all at once.

**Comment by woodruffw** [comment]
I agree that we should avoid reading inputs fully into memory, although I think we're actually limited by our dependencies in terms of actually doing this. For example, we use cryptography's [`EllipticCurvePrivateKey.sign`](https://cryptography.io/en/latest/hazmat/primitives/asymmetric/ec/#cryptography.hazmat.primitives.asymmetric.ec.EllipticCurvePrivateKey.sign), which only takes a `bytes` as input (not a file-like object).

We could maybe work/hack around that by using `mmap` and `bytearray`, but that requires investigation (and a confirmation from upstream that they intend to support non-`bytes`).

**Comment by jku** [comment]
oh I did not realize that -- this is disappointing from cryptography (I suppose the actual process still works with chunks at a time).

If it's an upstream issue then I'm fine with closing this as well: I expected this to be an easy fix not an issue with a dependency.

**Comment by woodruffw** [comment]
I'm okay with keeping it open for now! I think we should investigate the feasibility of using `bytearray`, and I can chat with the cryptography maintainers to see if they have any insights here.

**Comment by woodruffw** [comment]
One of the cryptography maintainers pointed out to me that ECDSA signing is defined by signing over the digest of the input rather than the full input, and that cryptography's API's actually support pre-hashing the input and passing that in instead of the full `bytes`.

As a result, this should actually be possible: we can stream the input into the digest function instead, and then pass `Prehashed(SHA256())` during signing instead of having the signing operating do the hash internally!

**Comment by woodruffw** [comment]
Doing this in #329.
