### ISSUE TITLE
Bring up our coverage and reenable coverage testing

### ISSUE THREAD

**Issue by tetsuo-cpp** [sigstore/sigstore-python#28]
We've temporarily disabled coverage testing while we're fleshing out the basic signing/verification functionality. Once things take a bit more shape, we should begin adding back coverage.

I expect this issue to be broken up into smaller PRs to test each module separately since there's probably quite a lot of work to do.

**Comment by woodruffw** [comment]
We'll probably want to do something similar to what we did on `pip-audit`, i.e. mark certain tests as "online" to emphasize that they need to connect to a CT log or some other service.

**Comment by woodruffw** [comment]
> Does `coverage` have any way to maintain state in the repo and make an assertion like "coverage has not dropped for any files"?

Not that I know of, unfortunately -- IIRC it uses a sqlite DB under the hood, which we could theoretically check in (if we don't mind the binary artifact), but I have no idea if they guarantee any amount of integrity/consistency between hosts.

We could consider a coverage provider, I believe `cryptography` has had moderate success with codecov (and our situation is thankfully simpler, since we're 100% Python with no platform specifics.)

**Comment by woodruffw** [comment]
I'm going to look into an online coverage provider, again -- our unit tests here require a certain amount of online functionality, so it doesn't make sense to enforce coverage on the client side (where tests might be skipped).

**Comment by woodruffw** [comment]
Looks like I don't have whatever org-level permissions are necessary to do this: I have Codecov enabled on my GitHub account and I can see Sigstore as one of my approved orgs, but none of the Sigstore repos show up in my dashboard.

**Comment by woodruffw** [comment]
Unblocked; turns out I was wrong about needing special permissions for Codecov. #253 has the changes.

**Comment by woodruffw** [comment]
@jleightcap will also be doing some work to bring the coverage up here.
