### ISSUE TITLE
Embed TUF targets to minimize downloads

### ISSUE THREAD

**Issue by haydentherapper** [sigstore/sigstore-python#608]
**Description**

For the Golang library, we embed a copy of the [target files](https://github.com/sigstore/sigstore/tree/main/pkg/tuf/repository/targets), and check if the target file matches the target metadata [here](https://github.com/sigstore/sigstore/blob/main/pkg/tuf/client.go#L522-L527) (a necessary check since the target file may have been updated and would need to be downloaded). Would it be possible to do the same for sigstore-python?

**Comment by di** [comment]
I think we'd need support from `python-tuf` before we can include the files here. Seems like this is the relevant issue: https://github.com/theupdateframework/python-tuf/issues/2225 (cc @jku)

**Comment by jku** [comment]
No, what hayden suggests is totally doable right now.

We discussed this during the original implementation and IIRC you or william did not want to embed the target files -- at least not without an automated systems that would make sure the embedded target files are up-to-date.

**Comment by woodruffw** [comment]
> We discussed this during the original implementation and IIRC you or william did not want to embed the target files -- at least not without an automated systems that would make sure the embedded target files are up-to-date.

I think that was probably me 🙂 -- my memory is a little fuzzy, but I think I remember being concerned that embedding here would mean older installs breaking over time. However, that shouldn't actually be true if my understanding of TUF is right, since we'll just refresh from the repo when the embedded targets are stale.

The other concern I remember was the cache priming feeling a little hacky -- IIRC it'd boil down to copying the embedded targets into the TUF repository's directory. But I don't remember why I was opposed to that; I think that's a reasonable tradeoff for minimizing TUF roundtrips 🙂

**Comment by jku** [comment]
> The other concern I remember was the cache priming feeling a little hacky -- IIRC it'd boil down to copying the embedded targets into the TUF repository's directory

That's how I'd do it. python-tuf will verify anything it finds in the local cache so this does not bypass any security measures if that's what you're thinking.

**Comment by haydentherapper** [comment]
The proposal is to bundle only the target files, not any other metadata (besides the initial TUF root, already embedded). With the new trusted_root file, you could embed only that. 

And correct, it shouldn’t break older installs because if the metadata digest doesn’t match what’s embedded, the client should download the freshest copy from the online repo.

**Comment by tetsuo-cpp** [comment]
@tnytown Are you already looking at this? If not, I can take a stab tomorrow.
