### ISSUE TITLE
Make `VerificationError` available in the API

### ISSUE THREAD

**Issue by mayaCostantini** [sigstore/sigstore-python#691]
**Description**

Make [`VerificationError`](https://github.com/sigstore/sigstore-python/blob/814bc6ba6081f98aeec90988759e8e233279f6af/sigstore/_cli.py#L856) defined in `sigstore/_cli.py` available in the verification API as it could be reused outside of the CLI.
See https://github.com/sigstore/sigstore-python/pull/692 for example implementation.

**Comment by woodruffw** [comment]
Thanks for filing this!

Could you say a bit more about your intended use case here? `VerificationError` really only gets used in the CLI, since the public and private APIs prefer to use the result-type-style `VerificationResult`/`VerificationFailure` instead.

**Comment by mayaCostantini** [comment]
This would be mostly for reuse in other CLIs that wrap `sigstore-python` functionalities. It also seemed to me like a generic error that could possibly be reused elsewhere by API users to raise from instead of returning  a result type value.

**Comment by woodruffw** [comment]
> This would be mostly for reuse in other CLIs that wrap sigstore-python functionalities. It also seemed to me like a generic error that could possibly be reused elsewhere by API users to raise from instead of returning a result type value.

Making sure I understand: by other CLIs, do you mean other Python programs that are importing `sigstore._cli` and re-using its internals? Doing so is understandable, but I'd prefer (for now) not to encourage that -- the `_cli` module and its interfaces are private and aren't considered part of `sigstore-python`'s semver contract, meaning that anybody who relies on them will experience frequent breakage as we move things around 🙂 

Overall, I think I'd prefer if we stick to the result-style API as the primary source of error state in the public APIs -- it's arguably less Pythonic, but it allows us to encode the error states in the type system rather than in an unchecked exception hierarchy. My experience with other end-user cryptography APIs (like `pyjwt`) is that using an exception hierarchy for these things inevitably leads to exception type leakage, which in turn means that users end up doing things like this:

```python
try:
   something()
except OurType:
   normal_failure_mode()
except Exception:
   weird_failure_mode()
```

...which in turn indicates a porous API and means that we can't make semver guarantees around error states, like we can currently.

Does that reasoning make sense to you? If so, I'm inclined to close #692 and keep these exception types private; IMO it might also make sense to add some documentation emphasizing the technical rationale above 🙂

**Comment by woodruffw** [comment]
Sounds good! I'll repurpose this issue to track that documentation.

**Comment by woodruffw** [comment]
FYI @mayaCostantini: we've refactored the verification APIs to be exception driven, so `VerificationError` will be part of the public API starting in the 3.x series 🙂 

xref https://github.com/sigstore/sigstore-python/pull/959
